#!/usr/bin/with-contenv bash

# Fetch & chown/chmod hotio's awesome "Arr Discord Notifier" script
# https://hotio.dev/arr-discord-notifier/
curl -fsSL -o /usr/local/bin/arr-discord-notifier https://raw.githubusercontent.com/hotio/arr-discord-notifier/master/arr-discord-notifier.sh
chown abc:abc /usr/local/bin/arr-discord-notifier
chmod +x /usr/local/bin/arr-discord-notifier

# Install MKVToolNix
# https://mkvtoolnix.download/
# ... and Python!
if [ -f /usr/bin/apt ]; then
  apt-get install --no-install-recommends -y mkvtoolnix python3-minimal python3-pip
elif [ -f /sbin/apk ]; then
  apk add --no-cache -u mkvtoolnix python3 py3-pip
fi

# Install Python dependencies and chown/chmod script
pip3 install iso_639_codes requests untangle
chown abc:abc /usr/local/bin/strip-tracks.py
chmod +x /usr/local/bin/strip-tracks.py